
import TanstackQueryProvider from "@/components/providers/TanstackQueryProvider";
import type { Metadata } from "next";

import '../styles/globals.scss';




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    
      <html lang="en">
        <body >
          <TanstackQueryProvider>
            

              {children}
            
          </TanstackQueryProvider>
        </body>
      </html>
    
  );
}

export default RootLayout
